# Generated by Django 4.0.5 on 2022-08-30 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_alter_patient_address_alter_patient_admitdate_and_more'),
        ('Appointment', '0002_alter_schedulerecord_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='Homepage.doctor'),
        ),
    ]
