# Generated by Django 4.0.5 on 2022-09-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_alter_schedule_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerecord',
            name='description',
            field=models.TextField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulerecord',
            name='service_name',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulerecord',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Created'), (2, 'Pending'), (3, 'Confirmed'), (4, 'Canceled'), (5, 'Edited')], default=1),
        ),
    ]
