# Generated by Django 3.2.12 on 2022-02-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_appointment_patientdischargedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='doctor01.jpg', null=True, upload_to='profile_pic/DoctorProfilePic/'),
        ),
    ]
