# Generated by Django 3.2.12 on 2022-05-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_auto_20220521_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pending',
        ),
    ]
