# Generated by Django 3.2.12 on 2022-08-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_auto_20220525_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Kişi', 'Kişi'), ('Qadın', 'Qadın')], default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
